CREATE TABLE about (
    id INT(11) AUTO_INCREMENT PRIMARY KEY,
    content TEXT
);
CREATE TABLE services (
    id INT(11) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255)
);
CREATE TABLE gallery (
    id INT(11) AUTO_INCREMENT PRIMARY KEY,
    url VARCHAR(255)
);
